version: '3.4'

x-logging:
  &default-logging
  driver: journald

x-labels:
  &default-labels
  org.supernetworks.ci: ${CI:-false}

services:
  mesh:
    container_name: supermesh
    image: ghcr.io/spr-networks/mesh_extension_mesh:${RELEASE_VERSION:-latest}
    build: .
    network_mode: host
    privileged: true
    logging: *default-logging
    labels: *default-labels
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "${SUPERDIR}./state/plugins/mesh:/state/plugins/mesh"
      - "${SUPERDIR}./configs/base:/configs/base"
      - "${SUPERDIR}./configs/mesh:/configs/mesh"
      - "${SUPERDIR}./state/public/:/state/public/:ro"
