name: Docker Image CI

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed
    branches: [ main, dev ]
  push:
    branches: [ dev ]

jobs:

  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      -
        name: Get version from git
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0 | grep -Eo '[0-9]+\.[0-9]+.[0-9]+')" >> $GITHUB_ENV
      -
        name: Test release tag version
        run: echo "RELEASE_VERSION == $RELEASE_VERSION"
      -
        name: Set up QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static

      # Install the cosign tool
      # https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Authenticate to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      -
        name: build options
        run: echo "tags:" "*.platform=linux/amd64,linux/arm64" "tags=mesh_extension_mesh:${RELEASE_VERSION:-latest}"

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ (github.event_name == 'workflow_run' && github.ref_name == 'main') || (env.RELEASE_CHANNEL != '' && github.event_name == 'push') }}
          tags: |
            ghcr.io/spr-networks/mesh_extension_mesh:${{ env.RELEASE_VERSION || 'latest' }}
            ghcr.io/spr-networks/mesh_extension_mesh:latest

      - name: Get images from docker-compose.yml
        id: get-images
        uses: mikefarah/yq@master
        with:
          cmd: yq -o json -I 0 '[.services|.[]|.image]' docker-compose.yml

      - name: Sign the images with GitHub OIDC Token
        if: ${{ (github.event_name == 'workflow_run' && github.ref_name == 'main') || (env.RELEASE_CHANNEL != '' && github.event_name == 'push') }}
        env:
          IMG1: ghcr.io/spr-networks/mesh_extension_mesh:${{ env.RELEASE_VERSION || 'latest' }}@${{ steps.build-and-push.outputs.digest }}
          IMG2: ghcr.io/spr-networks/mesh_extension_mesh:latest@${{ steps.build-and-push.outputs.digest }}
        run: |
          cosign sign --yes ${{ env.IMG1 }} ${{ env.IMG2 }}

      # Install the cosign tool
      # https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Sign the images with GitHub OIDC Token
        if: ${{ github.event_name == 'workflow_run' && github.ref_name == 'main' || env.RELEASE_CHANNEL != '' && github.event_name == 'push' }}
        run: |
          cosign sign --yes ${{ steps.extract_info.outputs.IMAGE_INFO }}

      - name: Prepare Attestation Matrix
        id: container_digests
        run: |
          matrix=$(echo ${{ steps.extract_info.outputs.IMAGE_INFO }} | jq -R -s -c 'split(" ") | map(split("@") | {name:  (.[0] | split(":")[0]), digest: .[1] | rtrimstr("\n") }) | group_by(.name) | map(.[0]) ')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

      - name: Set Matrix output
        id: set-matrix
        run: |
          echo 'name=matrix::${{ steps.get-images.outputs.result }}' >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      container_digests: ${{ steps.container_digests.outputs.matrix}}

  attest:
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
    needs: buildx
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_run' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image: ${{ fromJSON(needs.build-images.outputs.container_digests) }}

    steps:
      -
        name: Authenticate to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ matrix.image.name }}
          subject-digest: ${{ matrix.image.digest }}
          push-to-registry: true

#  sbom:
#    name: Generate SBOMs
#    needs: buildx
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        image: ${{ fromJson(needs.build-images.outputs.matrix) }}
#    steps:
#      - name: Generate SBOM
#        uses: anchore/sbom-action@v0
#        with:
#          image: '${{ matrix.image }}'
